x-uffizzi:
  ingress:
    service: app
    port: 80

  continuous_previews: 
    deploy_preview_when_image_tag_is_created: false
    deploy_preview_when_pull_request_is_opened: false
    delete_preview_when_pull_request_is_closed: false
    delete_preview_after: 720h

services:
  app:
    build: .
    deploy:
      resources:
        limits:
          memory: 4000M
    restart: always
    ports:
      - "80:80"
    privileged: true
    depends_on:
      - app
    cap_add:
      - SYS_ADMIN

continuous_preview:
  deploy_preview_when_pull_request_is_opened: false
  delete_preview_when_pull_request_is_closed: false
  delete_preview_in_x_hours: 720

volumes:
  data:
